### ISSUE TITLE
After upgrade to 2.7: __vite_ssr_import_0__.defineComponent is not a function

### ISSUE THREAD

**Issue by fallemand** [vueuse/vue-demi#182]
I have the current setup:

library:
- `vue-demi@0.13.6`

project1: 
- `vue@2.6`

project2: 
- `vue@3.1`

Everything was working fine until we migrated project1 to `vue@2.7`. After this, we get this error whenever we import something from the `library`:

```
11:00:16 [vite] Error when evaluating SSR module /@fs/Users/facundo.allemand/projects/traveler-frontend/node_modules/.pnpm/@getyourguide+compass@1.5.26-beta.49_typescript@4.4.3+vue@2.7.8/node_modules/@getyourguide/compass/index.ts?v=e717953f:
TypeError: __vite_ssr_import_0__.defineComponent is not a function
    at eval (/@fs/Users/facundo.allemand/projects/traveler-frontend/node_modules/.pnpm/@getyourguide+compass@1.5.26-beta.49_typescript@4.4.3+vue@2.7.8/node_modules/@getyourguide/compass/components/c-button/c-button.vue:33:41)
    at async instantiateModule (/Users/facundo.allemand/projects/traveler-frontend/node_modules/.pnpm/vite@2.8.4_sass@1.49.7/node_modules/vite/dist/node/chunks/dep-971d9e33.js:56177:9)
```

**Comment by wobsoriano** [comment]
Curious to see this. Do you have a simple repro? This is why I use render functions when doing vue2/3 compat library with vue-demi

**Comment by sxzz** [comment]
Could you please provide a minimum reproduction?
